<?php $additionalInfos = $block->getAllAdditionalInfo(); ?>

<?php if (isset($additionalInfos['mobipaid_transaction_id'])): ?>
    <div class="additional-information-item">
        <?= /* @noEscape */ __('Transaction ID') .' : ' . $additionalInfos['mobipaid_transaction_id'] ?>
    </div>
<?php endif; ?>

<?php if (isset($additionalInfos['mobipaid_status'])): ?>
    <div class="additional-information-item">
        <?= /* @noEscape */ __('Order Status') .' : ' . __($additionalInfos['mobipaid_status']) ?>
    </div>
<?php endif; ?>

<?php if (isset($additionalInfos['mobipaid_payment_id'])): ?>
    <div class="additional-information-item">
        <?= /* @noEscape */ __('Payment ID') .' : ' . $additionalInfos['mobipaid_payment_id'] ?>
    </div>
<?php endif; ?>
